'use strict';
// Spatialisation VBAP3D – adapté de Kandiskyscore (D.Blanchemain, GPL-3.0)

function owGenerateSpatDSP(layout, numInputs) {
  if (!layout || !layout.speakers) throw new Error('Layout VBAP3D invalide');
  const sp = layout.speakers;
  const M  = sp.length;
  const makeTable = field =>
    sp.map((s, i) =>
      `tabSpeaker${field.charAt(0).toUpperCase()+field.slice(1)}(${i}) = ${s[field]};`
    ).join('\n');

  return `
declare name    "${layout.name || 'SpatObject'}";
declare version "1.0";
declare author  "AutoGenerated – kandisky-interpretor";
declare license "BSD";

import("stdfaust.lib");

${makeTable('x')}
${makeTable('y')}
${makeTable('z')}
${makeTable('d')}

Matrix(N,M) = _*cdistance <: par(out, M, *(Fader(1,out) : si.smoo)) :> par(out, M, _)
with {
  dtencGen(in, out) = sqrt(pow(tabSpeakerX(out)-x(in),2) + pow(tabSpeakerY(out)+y(in),2) + pow(tabSpeakerZ(out)-z(in),2));
  hspot  = hslider("Hot Spot",-20,-50,0,1);
  dgain(in, out) = ba.db2linear((hspot/tabSpeakerD(out))*dtencGen(in,out));
  x(i)  = hslider("/X%i", 0,-1,1,0.01);
  y(i)  = hslider("/Y%i", 0,-1,1,0.01);
  z(i)  = hslider("/Z%i", 0,-1,1,0.01);
  Fader(in, out) = vgroup("[1]Input %2in", dgain(in,out));
  cdistance = hslider("dt", 1,0,1,0.1) : si.smoo;
};

process = par(j, ${numInputs}, _) :> Matrix(1, ${M});
`;
}

async function owCreateLayout(layoutName) {
  const paths = await window.api.getSpatPaths();
  const layout = await window.api.readLayoutJSON(layoutName);
  if (!layout) throw new Error(`Layout "${layoutName}" introuvable`);

  const dspSource = owGenerateSpatDSP(layout, 1);

  const faustIdx  = `file://${paths.faustWasm}/dist/esm/index.js`;
  const faustLib  = `${paths.faustWasm}/libfaust-wasm/libfaust-wasm.js`;

  const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler, FaustMonoDspGenerator } =
    await import(faustIdx);

  const faustModule = await instantiateFaustModuleFromFile(faustLib);
  const libFaust    = new LibFaust(faustModule);
  const compiler    = new FaustCompiler(libFaust);
  const generator   = new FaustMonoDspGenerator();

  await generator.compile(compiler, layoutName, dspSource, '');

  return {
    layout,
    generator,
    P: layout.speakers.length,
    createOfflineProcessor: (sampleRate, blockSize) =>
      generator.createOfflineProcessor(sampleRate, blockSize)
  };
}
